# Copy this file into one without .sample part and then populate it with actual values.
# Then you can create secret, by using command
# `sem create -f path/to/this/file`
# More info https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
apiVersion: v1beta
kind: Secret
metadata:
  # Use this name to create this secret manually
  name: production-env
data:
  files:
  # Server production.env file doesn't exist by default, copy sample.env into production.env
  # and populate with production values
  # Then create secret - in the end it should be here - https://<put-your-namespace-here>.semaphoreci.com/secrets
  - path: production.env
    # Could be created by
    # - `base64 -w 0 /path/to/file` and put in
    # - upload in https://<your-namesace>.semaphoreci.com/secrets
    content: PASTE_BASE64_ENCODED_CONTENT_HERE
  # Copy ormconfig.sample.json into ormconfig.production.json and populate with production values
  # You will need production connection settings in this config file.
  - path: ormconfig.production.json
    # Could be created by
    # - `base64 -w 0 /path/to/file` and put in
    # - upload in https://<your-namesace>.semaphoreci.com/secrets
    content: PASTE_BASE64_ENCODED_CONTENT_HERE
